# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 3, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralWidget)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableView.setObjectName("tableView")
        self.gridLayout_3.addWidget(self.tableView, 1, 2, 8, 1)
        self.horizontalFrame = QtWidgets.QFrame(self.centralWidget)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(self.horizontalFrame)
        self.commandLinkButton_5.setMaximumSize(QtCore.QSize(36, 16777215))
        self.commandLinkButton_5.setText("")
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.horizontalLayout_2.addWidget(self.commandLinkButton_5)
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.horizontalFrame)
        self.commandLinkButton_4.setMaximumSize(QtCore.QSize(36, 16777215))
        self.commandLinkButton_4.setText("")
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.horizontalLayout_2.addWidget(self.commandLinkButton_4)
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.horizontalFrame)
        self.commandLinkButton_3.setMaximumSize(QtCore.QSize(36, 16777215))
        self.commandLinkButton_3.setText("")
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.horizontalLayout_2.addWidget(self.commandLinkButton_3)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.horizontalFrame)
        self.commandLinkButton_2.setMaximumSize(QtCore.QSize(36, 16777215))
        self.commandLinkButton_2.setText("")
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.horizontalLayout_2.addWidget(self.commandLinkButton_2)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.horizontalFrame)
        self.commandLinkButton.setMaximumSize(QtCore.QSize(36, 16777215))
        self.commandLinkButton.setText("")
        self.commandLinkButton.setAutoExclusive(False)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout_2.addWidget(self.commandLinkButton)
        self.gridLayout_3.addWidget(self.horizontalFrame, 6, 0, 3, 2)
        self.label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("header_klein.png"))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 2, 2)
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(166777, 16777215))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        self.gridLayout_3.addWidget(self.listWidget, 5, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.frame)
        self.dateEdit_3.setAcceptDrops(False)
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.horizontalLayout_5.addWidget(self.dateEdit_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.frame)
        self.dateEdit_4.setCalendarPopup(True)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.horizontalLayout_5.addWidget(self.dateEdit_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.gridLayout_3.addWidget(self.frame, 0, 2, 1, 1)
        self.searchWidget = QtWidgets.QWidget(self.centralWidget)
        self.searchWidget.setObjectName("searchWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.searchWidget)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(self.searchWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.lineEdit = QtWidgets.QLineEdit(self.searchWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.checkBox_2 = QtWidgets.QCheckBox(self.searchWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.gridLayout_3.addWidget(self.searchWidget, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuDatei = QtWidgets.QMenu(self.menuBar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuAnsicht = QtWidgets.QMenu(self.menuBar)
        self.menuAnsicht.setObjectName("menuAnsicht")
        self.menuDatum = QtWidgets.QMenu(self.menuAnsicht)
        self.menuDatum.setObjectName("menuDatum")
        self.menuBearbeiten = QtWidgets.QMenu(self.menuBar)
        self.menuBearbeiten.setObjectName("menuBearbeiten")
        MainWindow.setMenuBar(self.menuBar)
        self.actionUeber = QtWidgets.QAction(MainWindow)
        self.actionUeber.setObjectName("actionUeber")
        self.actionEinstellungen = QtWidgets.QAction(MainWindow)
        self.actionEinstellungen.setObjectName("actionEinstellungen")
        self.actionLog = QtWidgets.QAction(MainWindow)
        self.actionLog.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionLog.setObjectName("actionLog")
        self.actionZeitpunkt = QtWidgets.QAction(MainWindow)
        self.actionZeitpunkt.setCheckable(True)
        self.actionZeitpunkt.setObjectName("actionZeitpunkt")
        self.actionZeitraum = QtWidgets.QAction(MainWindow)
        self.actionZeitraum.setCheckable(True)
        self.actionZeitraum.setObjectName("actionZeitraum")
        self.actionHeute = QtWidgets.QAction(MainWindow)
        self.actionHeute.setObjectName("actionHeute")
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionAuf_Update_berpr_fen = QtWidgets.QAction(MainWindow)
        self.actionAuf_Update_berpr_fen.setMenuRole(QtWidgets.QAction.ApplicationSpecificRole)
        self.actionAuf_Update_berpr_fen.setObjectName("actionAuf_Update_berpr_fen")
        self.action_ber_QT = QtWidgets.QAction(MainWindow)
        self.action_ber_QT.setMenuRole(QtWidgets.QAction.AboutQtRole)
        self.action_ber_QT.setObjectName("action_ber_QT")
        self.actionSpiele = QtWidgets.QAction(MainWindow)
        self.actionSpiele.setEnabled(False)
        self.actionSpiele.setObjectName("actionSpiele")
        self.actionImportieren = QtWidgets.QAction(MainWindow)
        self.actionImportieren.setObjectName("actionImportieren")
        self.actionReservierung = QtWidgets.QAction(MainWindow)
        self.actionReservierung.setEnabled(False)
        self.actionReservierung.setObjectName("actionReservierung")
        self.actionHinzuf_gen_reservieren = QtWidgets.QAction(MainWindow)
        self.actionHinzuf_gen_reservieren.setObjectName("actionHinzuf_gen_reservieren")
        self.actionL_schen = QtWidgets.QAction(MainWindow)
        self.actionL_schen.setObjectName("actionL_schen")
        self.actionAnsichtSpiele = QtWidgets.QAction(MainWindow)
        self.actionAnsichtSpiele.setCheckable(True)
        self.actionAnsichtSpiele.setChecked(True)
        self.actionAnsichtSpiele.setObjectName("actionAnsichtSpiele")
        self.actionAnsichtReservierungen = QtWidgets.QAction(MainWindow)
        self.actionAnsichtReservierungen.setCheckable(True)
        self.actionAnsichtReservierungen.setObjectName("actionAnsichtReservierungen")
        self.menuDatei.addAction(self.actionUeber)
        self.menuDatei.addAction(self.action_ber_QT)
        self.menuDatei.addAction(self.actionAuf_Update_berpr_fen)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionEinstellungen)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionBeenden)
        self.menuDatum.addAction(self.actionHeute)
        self.menuDatum.addSeparator()
        self.menuDatum.addAction(self.actionZeitpunkt)
        self.menuDatum.addAction(self.actionZeitraum)
        self.menuAnsicht.addAction(self.menuDatum.menuAction())
        self.menuAnsicht.addSeparator()
        self.menuAnsicht.addAction(self.actionAnsichtSpiele)
        self.menuAnsicht.addAction(self.actionAnsichtReservierungen)
        self.menuAnsicht.addSeparator()
        self.menuAnsicht.addAction(self.actionLog)
        self.menuBearbeiten.addAction(self.actionSpiele)
        self.menuBearbeiten.addAction(self.actionImportieren)
        self.menuBearbeiten.addSeparator()
        self.menuBearbeiten.addAction(self.actionReservierung)
        self.menuBearbeiten.addAction(self.actionHinzuf_gen_reservieren)
        self.menuBearbeiten.addAction(self.actionL_schen)
        self.menuBar.addAction(self.menuDatei.menuAction())
        self.menuBar.addAction(self.menuBearbeiten.menuAction())
        self.menuBar.addAction(self.menuAnsicht.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FuME - FuPa Match Explorer"))
        self.pushButton.setText(_translate("MainWindow", "ändern"))
        self.pushButton_11.setText(_translate("MainWindow", "reservieren"))
        self.pushButton_5.setText(_translate("MainWindow", "importieren"))
        self.pushButton_2.setText(_translate("MainWindow", "hochladen"))
        self.label_3.setText(_translate("MainWindow", "Auswahl modifizieren"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Noch keine Mannschaften hinzugefügt..."))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Region wählen und unten auf \"+\" klicken"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_13.setText(_translate("MainWindow", "Region:"))
        self.label_2.setText(_translate("MainWindow", "Von:"))
        self.label_4.setText(_translate("MainWindow", "Bis:"))
        self.label_6.setText(_translate("MainWindow", "Reservierung:"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" background-color:#b0ea99;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> erfolgreich<br /><span style=\" background-color:#eabdbe;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> fehlgeschlagen</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Suche:"))
        self.checkBox_2.setText(_translate("MainWindow", "markiert"))
        self.menuDatei.setTitle(_translate("MainWindow", "&Datei"))
        self.menuAnsicht.setTitle(_translate("MainWindow", "Ansicht"))
        self.menuDatum.setTitle(_translate("MainWindow", "Datum"))
        self.menuBearbeiten.setTitle(_translate("MainWindow", "Bearbeiten"))
        self.actionUeber.setText(_translate("MainWindow", "Über FuME"))
        self.actionEinstellungen.setText(_translate("MainWindow", "Einstellungen"))
        self.actionLog.setText(_translate("MainWindow", "Log anzeigen"))
        self.actionZeitpunkt.setText(_translate("MainWindow", "Zeitpunkt"))
        self.actionZeitraum.setText(_translate("MainWindow", "Zeitraum"))
        self.actionHeute.setText(_translate("MainWindow", "heute"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))
        self.actionAuf_Update_berpr_fen.setText(_translate("MainWindow", "Auf Updates überprüfen"))
        self.action_ber_QT.setText(_translate("MainWindow", "Über QT"))
        self.actionSpiele.setText(_translate("MainWindow", "Spiel"))
        self.actionImportieren.setText(_translate("MainWindow", "importieren (aus FuPa)"))
        self.actionReservierung.setText(_translate("MainWindow", "Reservierung"))
        self.actionHinzuf_gen_reservieren.setText(_translate("MainWindow", "hinzufügen (reservieren)"))
        self.actionL_schen.setText(_translate("MainWindow", "löschen"))
        self.actionAnsichtSpiele.setText(_translate("MainWindow", "Spiele"))
        self.actionAnsichtReservierungen.setText(_translate("MainWindow", "Reservierungen"))

